### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/activerecord-associations-video-review-blog-cli-with-activerecord-and-associations#2]
_Suggested Summary_
- In this video lecture, we build a Blog CLI gem to learn about CRUD with ActiveRecord and play around with associations between models.

_Suggested Objectives_
- Use ActiveRecord to persist data to a database so that you can access previously created material in different sessions (even though the garbage collector removes it from memory, each time). 
- Turn on ActiveRecord’s SQL log in Terminal so you can see what SQL statements are being executed by ActiveRecord, when you run your program.
- Recall that CRUD stands for _create_, _retrieve_, _update_, and _delete_.
- Separate the functionality of retrieving a user’s input by placing it in a method similar like _#user_input_ and then calling that method inside other methods where you need user input.
- Use _mass assignment_, to set numerous attributes of an object while it is being instantiated, via a hash passed into the argument of your constructor.
- Create and run necessary migrations to add columns to database tables, before using mass assignment to instantiate objects that correspond to those tables. 
- Add _ActiveRecord::Migration.check_pending_ to your console file to automatically make sure there are no pending migrations before you run the program.
- Use a _@current_user_ class variable and _.find_or_create_by_ as a way of tracking which user is currently using your application.
- Remember to replace _collection_ and _association_ with the name of the model when using methods from the ActiveRecord documentation. 
- Avoid using foreign keys in your code when you are assigning / creating attributes and objects—use high level assignors, given to you by ActiveRecord, instead. 
- Understand the benefits of using _.build_association_ to instantiate objects that are automatically associated (in memory) to the object that you built them off of. 
- Remember that the _shovel method_ (_<<_) returns all of the objects in the collection you are adding something to, and understand why that can be inefficient / dangerous.
- Avoid using _.create_, when possible—use _.build_, instead.
- Use _#each_ on a specific collection to print out each item in that collection for the user.
- Use _collection.find_ to find an object in a collection that has a specific attribute; and understand the SQL that is occurring under the hood, when you do so.
- Use _begin_ and _rescue_ keywords to gracefully handle a particular error that may occur in a block of code.
- Explain the difference in return values from _.find_ and _.find_by_ and why _.find_ tends to be more error prone.

**Comment by curiositypaths** [comment]
Thank you for submitting your suggested summary and objectives.
